name: Test Python files

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    
    - name: Run Python files
      run: |
        cd operators/addition
        python addition.py
        
        cd ../..
        cd operators/subtraction
        python subtraction.py
        
        cd ../..
        cd operators/multiplication
        python multiplication.py
