name: Test Python files

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    
    - name: Run Python files
      run: |
        python /operators/addition/addition.py
        python /operators/subtraction/subtraction.py
